### ISSUE TITLE
Android Build Fails "DirectoryNotFoundException: \Assets\Misc\Configs"

### ISSUE THREAD

**Issue by nipunasudha** [Deadcows/MyBox#11]
When I'm building for android, this error emerges.

![image](https://user-images.githubusercontent.com/17500323/54876344-59995e00-4e34-11e9-9eac-0eefa58fce67.png)

**Text version of the error**: https://pastebin.com/xp9Xgxk9

### How I fixed it:
I had to create the "\Assets\Misc\Configs" path, and a dummy file to prevent it from being auto removed.

![image](https://user-images.githubusercontent.com/17500323/54876336-4a1a1500-4e34-11e9-9057-6c2109a378a8.png)

**Comment by Deadcows** [comment]
I fixed it in the [latest commit ](https://github.com/Deadcows/MyBox/commit/d13f3c13a76322893eb966598b8f6107ec7d0bcf)

It was caused by my unfinished JsonDataManager tool which was made to operate json files as scryptableObjects on the fly. And on buildtime such json files was forsed to move from hardcoded path Musc/Configs to standalone build folder. I didn't know about streaming assets at the time :)

aaaanyways, I commented out this tool, maybe I'll got the time to finish this in the future. Thanks for bringing that out
