### ISSUE TITLE
[ButtonMethod] on ScriptableObjects

### ISSUE THREAD

**Issue by nipunasudha** [Deadcows/MyBox#15]
[ButtonMethod] attribute doesn't seem to work on ScriptableObjects. Is this intentional or is there any technical limitation?

[ButtonMethod] on ScriptableObjects would be so helpful to configure ScriptableObjects with ease.

**Comment by Deadcows** [comment]
I'm actually was lacking of this functionality as well but was too lazy to figure out how to fix it :) 
It is a technical limitation because SO and MB is derived from different types. 
...But it was pretty easy to solve, I just made two separate drawers, for SO and MB individually. 
So with[ this commit ](https://github.com/Deadcows/MyBox/commit/ce038dcb0064536b808cc7f9365bfd7fed0dd8ae)all works well! Thanks for pointing this out, useful feature :)
