### ISSUE TITLE
When unfoding lists/Array (To be precise, the CollectionWrapper), everything breaks up :)

### ISSUE THREAD

**Issue by DonTomasDeLaVega** [Deadcows/MyBox#151]
![image](https://user-images.githubusercontent.com/47381187/120617131-201ffc80-c45a-11eb-9dac-d8fbd186b58b.png)
As seen here! i saw that issue was old eneough, and i also saw this commit :
https://github.com/Deadcows/MyBox/commit/559fa1f866408cc3de9653e48f9799904e07aaf9
Do i need to install it in any way? Or is it supposed to be installed already if i installed the package this morning?
(It seems like the inspector thinks both folded and unfolded are the same size)
As we can see, folded lists works perfctly well 
![image](https://user-images.githubusercontent.com/47381187/120617638-9886bd80-c45a-11eb-8675-1b73fa0565ae.png)

**Comment by Deadcows** [comment]
Oh, this issue was specific to Collections inside of Displayed Inspector inside of Collections 😁
You marked the whole collection with DisplayInspectorAttribute? Cool usage, never thought of it!
Anyway, [I just fixed it](https://github.com/Deadcows/MyBox/commit/4d487668b98860460e2ecb70e8442d69d9add77d). This fix is not released as new version of MyBox yet, but you may Update it via "Tools/MyBox/MyBox Window" anyway. This way you'll get latest guthub version

**Comment by DonTomasDeLaVega** [comment]
Damn, updating is that easy? So clicking "Update UPM version" is enough? 😳

**Comment by Deadcows** [comment]
> Damn, updating is that easy? So clicking "Update UPM version" is enough? 😳

haha hopefully updater won't break this time 😅 but yeah, should be pretty easy
