### ISSUE TITLE
Serializable Dictionnary showing unnecessary "Array" variable.

### ISSUE THREAD

**Issue by DonTomasDeLaVega** [Deadcows/MyBox#158]
https://wiki.unity3d.com/index.php/SerializableDictionary
Hi! i'm using a serializable dictionnary package, and works juste fine.
![image](https://user-images.githubusercontent.com/47381187/121313938-2e14c800-c907-11eb-8949-72bfcc8706ed.png)
But when i've got a "ShowInspector" attribute on it, a weird "Array" variable shows up:
![image](https://user-images.githubusercontent.com/47381187/121313987-3b31b700-c907-11eb-8f0d-be2e96a8ca7a.png)
And it blocks up the view... I just need it not to show in the first place. I wanted to implement the SerializableDictionary.cs here, but it's weirdly integrating, and i cant attach it as a file, sorry

**Comment by Deadcows** [comment]
They are using private serialized field called "Array" and DisplayInspector is building up the whole inspector  of the object looking up for all serialized fields, but I'm not sure why my DisplayInspector is unable to properly calculate height of this field. 
The best thing you can do is to fold this Array field, at least inspector don't looks like it broken this way...

![image](https://user-images.githubusercontent.com/969858/121348203-b6f42980-c930-11eb-8d43-cd48d3fdeeb5.png)

If you for some reason downloaded their package as set of .cs files (not as a package via PackageManager) you should be able to edit their code. This way you may try to change SerializableDictionary.cs on line 13 and add HideInInspectorAttribute to array field:

`[UnityEngine.SerializeField, HideInInspector] private Pair[] array;`


anyway, it's not a solution for your problem, but I won't be able to fully support compatibility with other packages. 
Especially because I'd like to create my own SerializableDictionary someday, fully integrated 😏

**Comment by DonTomasDeLaVega** [comment]
ooooooh, i'd be looking forward to that 😉 
Thanks for your reactivity and for your free tools, i really like em!
