### ISSUE TITLE
Misleading RandomInRange(this MinMaxFloat minMax) summary comments

### ISSUE THREAD

**Issue by hamtaren** [Deadcows/MyBox#162]
Hi, I got mislead a little, by `RandomInRange(this MinMaxFloat minMax)` and `RandomInRangeInclusive(this MinMaxFloat minMax)` effects and comments in summary.

Since `Random.Range` (while using `float`) is [minInclusive..maxInclusive] and `int` [minInclusive..maxExclusive] when I got my minMax set:
min: 0.75f, max: 1.0f
I got output range from:
0.75f to 2.0f
while using `RandomInRangeInclusive(this MinMaxFloat minMax)`.
I know the intentions behind it, especialy for the `ints`, but for `floats` comment in `RandomInRange's` summary is misleading:
![image](https://user-images.githubusercontent.com/14167120/123636876-a6dbb580-d81d-11eb-8636-a7409c8fb967.png)

I don't know how it could be done better, I thought I'd just report this, because it might be tricky to change `RandomInRange` into `RandomInRangeExclusive` and `RandomInRangeInclusive` into `RandomInRange`.

**Comment by Deadcows** [comment]
Thanks for the report! I made this extensions for MinMaxInt and blindly copypasted them for MinMaxFloat. 
RandomInRangeInclusive for MinMaxFloat [is removed](https://github.com/Deadcows/MyBox/commit/69e90a289eecee5c1c0ba25ac34ccd52e0c249d4) (since it's inclusive already) and summary changed for MinMaxFloat.RandomInRange accordingly
