### ISSUE TITLE
Issue when wanting to "Display Inspector" on a CollectionWrapper of my ScriptableObject.

### ISSUE THREAD

**Issue by DonTomasDeLaVega** [Deadcows/MyBox#164]
Here is the issue: `type is not a supported pptr value
UnityEditor.SerializedProperty:get_objectReferenceValue ()
MyBox.Internal.DisplayInspectorAttributeDrawer:OnGUI (UnityEngine.Rect,UnityEditor.SerializedProperty,UnityEngine.GUIContent) (at Library/PackageCache/com.domybest.mybox@725b8fb2ca/Attributes/DisplayInspectorAttribute.cs:54)
MyBox.Internal.ConditionalFieldAttributeDrawer:<OnGUI>g__TryUseAttributeDrawer|6_0 (MyBox.Internal.ConditionalFieldAttributeDrawer/<>c__DisplayClass6_0&) (at Library/PackageCache/com.domybest.mybox@725b8fb2ca/Attributes/ConditionalFieldAttribute.cs:83)
MyBox.Internal.ConditionalFieldAttributeDrawer:OnGUI (UnityEngine.Rect,UnityEditor.SerializedProperty,UnityEngine.GUIContent) (at Library/PackageCache/com.domybest.mybox@725b8fb2ca/Attributes/ConditionalFieldAttribute.cs:74)
UnityEditor.EditorGUILayout:PropertyField (UnityEditor.SerializedProperty,bool,UnityEngine.GUILayoutOption[])
MyBox.Internal.FoldoutAttributeHandler:Body () (at Library/PackageCache/com.domybest.mybox@725b8fb2ca/Attributes/FoldoutAttribute.cs:113)
MyBox.Internal.FoldoutAttributeHandler:OnInspectorGUI () (at Library/PackageCache/com.domybest.mybox@725b8fb2ca/Attributes/FoldoutAttribute.cs:83)
MyBox.Internal.UnityObjectEditor:OnInspectorGUI () (at Library/PackageCache/com.domybest.mybox@725b8fb2ca/Tools/Internal/UnityObjectEditor.cs:34)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
`
It doesn't seem to like it one bit ^^'
I can do without, but i'd like to do with it ^^'
Here's my code:
![image](https://user-images.githubusercontent.com/47381187/123935778-d2cd7700-d994-11eb-9709-ffba74f31c0b.png)
[...]
![image](https://user-images.githubusercontent.com/47381187/123935677-b92c2f80-d994-11eb-849b-3018b53377ea.png)
And when i add, after the conditionnal field, a displayInspector attribute, unity loses its mind

**Comment by Deadcows** [comment]
Very interesting feature you want here! The problem actually is not in ConditionalField. DisplayInspector is made to work with SO or MB field, and CollectionWrapper is not one of those. I'm not sure it'll be possible to make it to work.

Try to use Foldout instead of Conditional! I just reworked it's visual yesterday, it looks neat 🤓

```
[Foldout("Leaf Creation"), DisplayInspector]
public BookContext[] Contexts;
[Foldout("Leaf Creation"), DisplayInspector]
public Item[] Items;
```
![image](https://user-images.githubusercontent.com/969858/130190641-a19583f9-0f4b-491d-be66-23ce5b016ef3.png)

Ability to use DisplayInspector with collection along with ConditionalField looks nice, I will add it to my to-do, but I'd wouldn't expect it any soon 🙄

btw sorry for the late responce! Abandoned MyBox for a few months with all the crunches with my game 🤯

**Comment by Deadcows** [comment]
But I [fixed ](https://github.com/Deadcows/MyBox/commit/7da724cb1b8ccfd4381fe2455839714704968b8b) this error spamming! DisplayInspector now will show warning if used on property of the wrong type

![image](https://user-images.githubusercontent.com/969858/130194549-fec57307-63cd-47cc-947b-3d222e9e1029.png)
