### ISSUE TITLE
Request : Adding a .ToArray() methods on collection wrappers

### ISSUE THREAD

**Issue by DonTomasDeLaVega** [Deadcows/MyBox#165]
Could be usefull, but i really don't know how to do this ^^'

**Comment by Deadcows** [comment]
Sorry for a late response, I'm occupied with my working project.

What are you trying to achieve with collection wrapper? 
CollectionWrapper is an empty class with the only field of your array. If you want to access this array, simply use _wrapper.Value and if you want to copy the array for some reason, you may use Array.Copy method. 
The only reason CollectionWrapper exists, because it's impossible to use custom attributes on array fields in unity. It got zero functionality by itself.

Anyway, I'm interested, how you're using wrappers in your project?
