### ISSUE TITLE
Conditional attributes don't work with properties

### ISSUE THREAD

**Issue by Tommigun1980** [Deadcows/MyBox#188]
Hello and thanks for a great library!

However I found a slight issue (or lack of feature), namely that the conditional attributes (and possibly some other attributes, didn't check) only seem to work with fields and not with properties. So this won't work:

```c#
            [SerializeField]
            private bool someBool;
            public bool SomeBool
            {
                get { return this.someBool; }
            }

            [SerializeField]
            [ConditionalField(nameof(SomeClass.SomeBool))]
            private SomeInnerClassData someInnerClass;
            public SomeInnerClassData SomeInnerClass
            {
                get { return this.someInnerClass; }
            }
```

It does work if someBool is made public and bound to directly, but that breaks data encapsulation. It is quite convenient to have fields that are only editable through data.

So please consider adding support to ConditionalField attributes to also check for properties and not just fields!

Thank you so much.

**Comment by snappedToGrid** [comment]
Hey there! 
I just tried adding AttributeTargets.Property to the ConditionalFieldAttribute class definition, and it actually seems to be working 😮 

This is the class definition 
```
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field)]
	public class ConditionalFieldAttribute : PropertyAttribute

```


And this is how I use it with an actual property

```
[field:SerializeField]
        [field:ConditionalField(true, "IsCool")]
        public Object MyObj { get; private set; }
        
        bool IsCool()
        {
            return NameProperty== "Coolio";
        }
```

As you can see, I did have to resort to using a function to check instead of just a simple field check, because my other field was also a property. But it seems to do the job!

**Comment by Deadcows** [comment]
Merged the fix. Thanks @snappedToGrid!
