### ISSUE TITLE
ConditionalField breaks multi-editing in inspector

### ISSUE THREAD

**Issue by nipunasudha** [Deadcows/MyBox#21]
As I just discovered, [ConditionalField] breaks the multi-object editing when multiple instances of a ScriptableObject are selected. And this is a crucial feature to have when dealing with a lot of ScriptableObjects.

Can you please take a look? I myself is following some editor tips to amend this behavior, if I find a solution or a workaround (e.g. hiding only the unsupported fields when multi-selected), I'll let you know.

**Comment by Deadcows** [comment]
Thanks you so much for pointing this out. I never checked multi-object editing and just figured out that MyBox simply breaks this feature 0_o

Probably because some of the scripts hooks to every object and prevents it from multi-edition. I think MustBeAssigned may cause this. I'm currently investigating this issue

**Comment by Deadcows** [comment]
I came to that when I made empty SO script (no fields and logic) and created a few assets out of it and without any attributes those assets not supports multi-object edition. Then I tried in a blank project without MyBox and all were fine

**Comment by Deadcows** [comment]
So, I found the culprit. Surprisingly, ButtonMethod caused this issue for all ScriptableObjects in project.
Fixed in [this commit](https://github.com/Deadcows/MyBox/commit/f35a0875b1e9e83ded02fdbbc8a44ca1d5cfce07)
Please check this out and let me know if issue with multi-editing remains in some other places with MyBox
