### ISSUE TITLE
Loopable animations not working with AnimationStateReference play extension

### ISSUE THREAD

**Issue by VirsabiMunk** [Deadcows/MyBox#63]
I'm using this code for previewing animation states out of playmode in the editor;

```
/// <summary>
/// Script to change animation states in editor to preview states in scene
/// </summary>

#if UNITY_EDITOR
[RequireComponent(typeof(Animator))]
[ExecuteInEditMode]
public class AnimationStateInEditor : MonoBehaviour
{
    [AutoProperty, ReadOnly, SerializeField]
    private Animator anim;
    
    public AnimationStateReference state;

    private void OnValidate()
    {
        anim = GetComponent<Animator>();
    }

    private void Update()
    {
        if (!Application.isPlaying)
        {
            //forces to play in edit mode
            anim.Update(Time.deltaTime);
            anim.Play(state);

        }
            
    }
}
#endif
```

While normal animations work fine, loopable animations only plays the first few frames over and over - not the entire animation. Am I doing something wrong here?

**Comment by Deadcows** [comment]
Yep, I guess I see the problem. But I think normal animations probably should behave same way, like the looping ones. 
Play method is not just telling "keep playing", it's starting animation from the beginning. And you calling it in the Update method. In editor Update calls much less frequently comparing to playmode (it might be 1-2fps but it depends) so you starting the animation from the beginning over and over a few times a second.

Instead of simply calling it in Update you need to check if state.StateName was changed, and if it was => Play the new state. 
It might be enough but I'm not sure how looping animations will behave in edit mode.
Also for looping animations you may either access playable graph of the animator and check for "ifPlaying", and Play if it is not or you may somehow get animation clip time length and Play every time elapsed time is => clip length. 

I didn't do such things, but it's my first ideas

Also, such method might be helpful in your case if something stucks

    [ButtonMethod]
    private void PlayAnimation() => anim.Play(state);

**Comment by Deadcows** [comment]
Oh also AutoProperty should make field read only anyway, you don't need to use ReadOnly attribute. 
But I'm not sure how well AutoProperty will work in this case, in editor. AutoProperty collects values when scene is saved, and it happened OnPlaymode.
This way if you just put this MB on GO and did not saved the scene, anim will be null.
In this particular case you may access cached animator through AnimationStateReference.

    if (Application.isPlaying) return
    if (!state.Assigned) return;

    state.Animator.Update(Time.deltaTime);
    state.Play();

**Comment by VirsabiMunk** [comment]
Isn't that what's happening already in your extension?

```
public static class AnimationStateReferenceExtension
	{
		public static void Play(this Animator animator, AnimationStateReference state)
		{
			if (!state.Assigned) return;
			animator.Play(state.StateName);
		}
	}
```

Using the button method it seems like some of my animations that should loop just runs once and goes into my idle state. Does this method take the animation controller transitions into consideration? Otherwise I have no idea why that's happening.

**Comment by Deadcows** [comment]
Yep, it simply plays animation on the Animator with all the translations and stuff. 
To separate particular animation you probably need to parse animator controller to receive AnimationClip asset, construct new playable graph on the fly and inject your clip asset and playable output (animated avatar). It's been a while since I dabbled with playables, but it should be relatively easy to do the thing you want
There are some links that may help: [Playable example](https://docs.unity3d.com/Manual/Playables-Examples.html), [SimpleAnimation example project](https://github.com/Unity-Technologies/SimpleAnimation) and also it seems that legacy [Animation component might work](https://docs.unity3d.com/ScriptReference/Animation.AddClip.html)

**Comment by Deadcows** [comment]
Share your results when this tool is done if it's possible 😉 I'd like to see how you're using this animation preview mode in your game🤓
