### ISSUE TITLE
Errors with Reorderable

### ISSUE THREAD

**Issue by esp1001** [Deadcows/MyBox#66]
![image](https://user-images.githubusercontent.com/12458439/79069814-e92cdb80-7cd9-11ea-8bbd-3aafebc8985d.png)

Unity 2019.3.9f1

**Comment by Deadcows** [comment]
Oh my, sorry for the late response! 
Finally I've got some time for MyBox 😊
This issue is [finally fixed](https://github.com/Deadcows/MyBox/commit/37abc8b9a381b4033c36a6a42c6835faba2aed57)

Update MyBox with Tools/MyBox/UpdateMyBox 👍🏻

![image](https://user-images.githubusercontent.com/969858/80684892-0bdb3480-8acf-11ea-8ba6-2f57ff0080c2.png)
