### ISSUE TITLE
Serialize methods using SceneReference as argument in Inspector?

### ISSUE THREAD

**Issue by tonygiang** [Deadcows/MyBox#78]
Methods that take a `SceneReference` as an argument currently cannot be called by an event in Inspector, like the OnClick event of a button. Is it possible to make this work?

**Comment by Deadcows** [comment]
As far as I know UnityEvents supports only methods with single parameter of primitive type or with type inherited from UnityEngine.Object. 
So it is doable but you need to create ScriptableObject wrapper for ... SceneReference reference. 
It's not perfect but it works. 


````
public UnityAction ActionWithSceneReference;
	
public void MethodWithSceneReference(SceneReferenceSO scene)
{
	scene.Scene.LoadScene();
}

...

[CreateAssetMenu]
public class SceneReferenceSO : ScriptableObject
{
	public SceneReference Scene;
}
````

![image](https://user-images.githubusercontent.com/969858/83177865-701e0200-a128-11ea-8f85-114a02a3236a.png)
![image](https://user-images.githubusercontent.com/969858/83178373-18cc6180-a129-11ea-8a93-0eb4e90b9ebd.png)

How do you want to use SceneReference with actions? Maybe we will come up with a better solution for your use case

**Comment by tonygiang** [comment]
I structure my scenes as followed:
Scene 1 with buttons to load other scenes asynchronously.
Before Scene 2, 3, 4 finished loading, Scene 1 will play fade-out transition. Scene 1 unloads when fade-out ends.
Scene 2, 3, 4 will begin showing visible elements as soon as the fade-out ends or as soon as they finish loading, whichever event happens last.
Scene 1 rout all of these scene load event through a common, game-wide event, currently using a string to identify which scene is being loaded so they can be filtered when invoking. For example: When scene 2 and 3 are loaded, but only scene 2 is visible, and this event fires off with "Scene 3" as an argument, scene 2 filters it out and do nothing, but scene 3 will process this event.

This workflow breaks when we have to rename scenes to avoid naming conflicts with new scenes we receive in our projects. Our underline goal is just to have a reliable way to pin-point Button A will send a signal to scene 2, Button B will send a signal to scene 3, etc... with the peace of mind of reference types that we don't have to do anything else when we rename our objects.

**Comment by Deadcows** [comment]
I'd add a "SceneLoadButton" script on every button or something like that, with LoadScene method and SceneReference field. I believe that's would be the easiest solution

![image](https://user-images.githubusercontent.com/969858/83225233-f74e9280-a187-11ea-9fe8-842d23ee0eb0.png)

Or even better to change minimally your current approach, you probably have some SceneLoader MB with LoadScene(string scene) method which you bind with button OnClick. 
So you may add SceneWrapper mb and place it on your button and instead of string pass SceneWrapper into your LoadScene method like so

````
public class SceneReferenceWrapper : MonoBehaviour
{
    public SceneReference Scene;
}
````

![image](https://user-images.githubusercontent.com/969858/83225861-5cef4e80-a189-11ea-9158-59000c351a3e.png)
