### ISSUE TITLE
CollectionWrapperBase could not be found when building the project

### ISSUE THREAD

**Issue by Kryloth** [Deadcows/MyBox#79]
Hello can you help me ?, i don't know what happened but when I tried to build my project there's an error that says

`Assets\MyBox-1.4.0\Types\CollectionWrapper.cs(7,38): error CS0246: The type or namespace name 'CollectionWrapperBase' could not be found (are you missing a using directive or an assembly reference?)
`

I didn't touch any of the original plugin code so I'm not sure why that happened

**Comment by Kryloth** [comment]
Nevermind, it's my own fault
i installed MyBox incorrectly by downloading the entire file in zip and just extract it into my unity project

I deleted my MyBox folder and this time install it properly by installing it from Unity package manager using the git link

**Comment by kirpit** [comment]
I was also using the checked out folder from repository instead of installing via the package manager. Switched to open upm installation (version 1.4.0) as per the suggestion but since the code is exactly the same, it kept giving the exact same error. I'm not sure how yours is different but I come to believe this is purely about the code.

There is the `CollectionWrapper<T>` class inheriting from `CollectionWrapperBase` and this base class is in the same file but within the `#if UNITY_EDITOR .... #endif` block...

I've edited the file `Library/PackageCache/com.mybox@1.4.0/Types/CollectionWrapper.cs` and simply created an empty base class outside the editor specific code:
```
public class CollectionWrapperBase {}
```
and it successfully finished the build and was able to run in my mobile, despite to some code warnings shown below.

![image](https://user-images.githubusercontent.com/1009931/83752664-40cd3f00-a6ac-11ea-95bf-6a4d64ff87d7.png)

**Comment by Deadcows** [comment]
I just uploaded 1.4.1 version with this fix. 
Please try to update via Tools/MyBox/MyBoxWindow and let me know if this problem remains

**Comment by kirpit** [comment]
Hi @Deadcows, thanks for fixing this. It was giving some warnings with 1.4.1 but successfully made the build.
