### ISSUE TITLE
Feature Request: Disable update checking

### ISSUE THREAD

**Issue by carreraSilvio** [Deadcows/MyBox#91]
Sometimes my wifi varies a bit and I keep getting warnings about not being able to check for updates. So an option to disable entirely or only check on startup would be nice.

**Comment by Deadcows** [comment]
Agree. Sorry for spamming :) I disabled this message completely [in the latest commit](https://github.com/Deadcows/MyBox/commit/03c6389984788b249f9b827ec3092dd7361b3d19). 
At the other hand it still will spam in console every time on recompile if there is new version. I'll fix this in the next version

**Comment by carreraSilvio** [comment]
Hey! Has this been implemented? :) 
![image](https://user-images.githubusercontent.com/3154359/114276884-fbca1580-99fe-11eb-981c-4a83d7fbacd7.png)

**Comment by Deadcows** [comment]
This issue was about "not able to check for updates". And in your case, apparently, and here MyBox is.. very able to check for updates 😁 

The problem might be, that one of the last versions messed up Settings file and you need to disable Update Checking again. 

Can you please tell me, you got this message every time project compiles? I wanted to check for updates only once, but was unable to find how to call some code ONLY ONCE WHEN EDITOR OPENS 😑

**Comment by Deadcows** [comment]
Phew, finally! In the next version MyBox will [check for updates only once](https://github.com/Deadcows/MyBox/commit/e6e7fd745355582d0d7785aaea63270068351999?w=1)!

**Comment by carreraSilvio** [comment]
Thanks @Deadcows! That's awesome, man! Wish you all the best :)
